### ISSUE TITLE
data loading and data processing

### ISSUE THREAD

**Issue by hengguo-boop** [starVLA/starVLA#13]
First of all, thank you for your excellent work. 
I have a question here. What are the differences between your data loading and data processing and the original gr00t? 
I encountered an "Attempt 9/10 failed for index 415499: [Errno 12] Cannot allocate memory" memory overflow issue. 
It occurs when batch_size is set to 48, which is relatively large. The training is normal with the default pre_batch_size of 16. I would like to know why this problem occurs. My server has a relatively large storage capacity.

**Comment by Yioutpi** [comment]
Thank you for your interest in our work!

1. Our dataloader is inherited from GR00T, but we added several settings in `datasets.py`, including filtering out trajectories without instructions, removing pause frames, and pre-caching all frame indices (to reduce initialization overhead for large datasets). Apart from these modifications, our data preprocessing and data configuration are almost identical to those used in GR00T.
2. We tested data loading with `datasets.vla_data.per_device_batch_size=48` on our cluster, and it worked normally. However, during model forward passes, GPU OOM may occur even on GPUs with 80 GB memory. If you’ve successfully run it on GPUs with larger memory, we’d appreciate it if you could share your configuration. Regarding the “[Errno 12] Cannot allocate memory” error you encountered during data loading, could you please share more details about your machine setup and environment versions?

**Comment by hengguo-boop** [comment]
Thank you for your prompt reply!
It seems that the issue has been resolved for now. I used the [torchcodec from the original gr00t](https://github.com/NVIDIA/Isaac-GR00T/blob/a86e9159a7e6acf771479007a79d4aeaa408c4c0/gr00t/utils/video.py#L101) instead of pyav. 
The training is now running smoothly. 
Thank you again for your excellent work. 
I'll provide the memory overflow issue below for your reference.We are testing the H200 machine in the same environment as yours.
```
rank3]: File "/datashare/code/starVLA/starVLA/dataloader/gr00t_lerobot/datasets.py", line 1573, in __getitem__ 
[rank3]: data = dataset.transforms(dataset.get_step_data(trajectory_name, step)) 
[rank3]: File "/datashare/code/starVLA/starVLA/dataloader/gr00t_lerobot/datasets.py", line 798, in get_step_data 
[rank3]: data[key] = self.get_data_by_modality(trajectory_id, modality, key, base_index) 
[rank3]: File "/datashare/code/starVLA/starVLA/dataloader/gr00t_lerobot/datasets.py", line 1059, in get_data_by_modality 
[rank3]: return self.get_video(trajectory_id, key, base_index)
[rank3]: File "/datashare/code/starVLA/starVLA/dataloader/gr00t_lerobot/datasets.py", line 928, in get_video 
[rank3]: return get_frames_by_timestamps(
[rank3]: File "/datashare/code/starVLA/starVLA/dataloader/gr00t_lerobot/video.py", line 146, in get_frames_by_timestamps 
[rank3]: for frame in reader: 
[rank3]: File "/datashare/miniconda3/envs/starVLA/lib/python3.10/site-packages/torchvision/io/video_reader.py", line 200, in __next__ 
[rank3]: frame = next(self._c) 
[rank3]: File "av/container/input.pyx", line 208, in decode 
[rank3]: File "av/packet.pyx", line 80, in av.packet.Packet.decode 
[rank3]: File "av/video/stream.pyx", line 41, in av.video.stream.VideoStream.decode 
[rank3]: File "av/video/stream.pyx", line 50, in av.video.stream.VideoStream.decode 
[rank3]: File "av/codec/context.pyx", line 462, in av.codec.context.CodecContext.decode
[rank3]: File "av/codec/context.pyx", line 238, in av.codec.context.CodecContext.open 
[rank3]: File "av/error.pyx", line 326, in av.error.err_check 
[rank3]: av.error.MemoryError: [Errno 12] Cannot allocate memory
```
Additionally, I have a few questions: 
1. Will you optimize this part of the problem in the future? 
2. Regarding your data preprocessing, will you consider methods like pi or wallx for pre-computing compute_norm_stats separately (including your data optimization, such as removing static frames, etc.)? Because I saw in your readme that preprocessing does not take more time, will this also be the case for large-scale datasets? 
3. Will you consider adding wallx's data loading and robot modal processing methods? Currently, gr00t only does single robot body feature marking for EmbodimentTag, while wallx has 32-dimensional state marking to fill any state. Do you think this method is better? 
If there are any mistakes in my questions, please correct me. Looking forward to your reply again!

**Comment by Yioutpi** [comment]
1. We previously resolved the “Cannot allocate memory” issue by adjusting the **`av`** version. You may try **`av==12.3.0`** or **`av==14.4.0`**, along with **`torchvision==0.21.0`**. We plan to further test and optimize this problem across more computing platforms in the future.
2. Thank you for your suggestions regarding data preprocessing. We are also improving this part. Compared to model training, data preprocessing indeed doesn’t take much time; the main cost lies in retrieving all frame indices. However, this collection happens only during the first run for each dataset and is cached afterward. In our tests, processing 240k trajectories took about 2 hours, though the exact time depends on your computing platform.
3. We are also exploring more compatible and accessible data loading approaches for different embodiments. Currently, we pad raw data to align actions and states for each embodiment, but we plan to support multi-dimensional unified formats similar to the original GR00T or wallX implementations in the future. For now, our priority is to expand benchmark evaluations. If you have a well-optimized implementation for data preprocessing or loading, contributions via **PRs** are very welcome.

**Comment by SuLvXiangXin** [comment]
The problem still exists using torchvision_av backend for video loading. And it can be solved by switching to decord.

**Comment by JinhuiYE** [comment]
Yes, you are absolutely right. We have indeed set decord as the default backend in our codebase to resolve this issue.

However, please note that on some A100 GPUs, there might be compatibility issues with decord due to its specific hardware decoding requirements. If you encounter any problems on such hardware, you may need to consider switching back to an alternative backend.

**Comment by EmberNoWeither** [comment]
I tried av==16.1.0 and the latest ffmpeg for h200 gpus. This works.
